project:
  type: website
  output-dir: docs

website:
  title: "Etienne Henry"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

bibliography: references/refs.bib