project:
  type: website
  output-dir: docs

website:
  title: "Etienne Henry"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd

format:
  html:
    theme: cosmo
    toc: true

editor: visual

bibliography: references/refs.bib
csl: references/acta-naturae.csl #https://www.zotero.org/styles?fields=biology&format=numeric