---
title: "Education"
---

-   **2022-2023**: École Normale Supérieure de Lyon, Lyon, France\
    Agrégation in Life and Earth sciences (national examination to become a qualified professor in France)\
    Ranked 7th (out of \>400 candidates)

-    **2021-2022:** 2nd year Master Degree Conservation sciences National Museum of Natural History, Paris, France\
    2nd year Master degree with highest honors (17.0/20)\
    [Classes]{.underline}: biogeography & macroecology, biostatistics, population viability, socio-ecosystem functioning, GIS

-   **2020-2021**: 1st year Master degree École Normale Supérieure, Paris, France\
    Ecology & Evolution\
    1st year Master degree with highest honors (16.6/20)\
    [Classes]{.underline}: ecosystem functionning, evolutionary ecology, data analysis, biostatistics, modelling

-   **2019-2020:** École Normale Supérieure, Paris, France**\
    **BSc Life sciences Bachelor’s degree with honors (15,84/20)\
    [Classes]{.underline}: ecology, evolution, experimental ecology, biostatistics, programming

-   **2017-2019**:\
    Preparatory classes Life and Earth sciences Champollion High School, Grenoble, France\
    Two-year undergraduate intensive courses in Earth and Life sciences in preparation to the highly competitive exam for admission to the French ”Grandes Écoles”, leading to admission in the École Normale Supérieure (French highest ranked school in research). 2016-2017 1st year engineer school Agronomy EI Purpan agronomist school, Toulouse, France ⋅ Top of the class (out of \>200 students)
