---
title: "Teaching"

theme: #Sandstone #https://bootswatch.com/
  light: flatly
  dark: darkly
---

This facet holds special significance for me as I seek to balance my career between teaching and research.

### Behavioral ecology

*1st and 2nd year bachelor students*

Practical classes: \
 - Use of software BORIS and hierarchy calculation\
Lecture:\
- Social behaviour

### Ecosystem functioning

*3rd year bachelor students*

Practical classes: - Primary production, decomposition of organic matter, herbivory

### Evolution

*2nd year bachelor students*

Tutorial classes

Introduction to evolutionary concepts:\
- **Micro-evolution**: heritability, forces of evolution (haploids and diploids)\
- **Macro evolution**: phylogeny and evolution (gradualism vs punctuated equilibrium), speciation (allopatric, sympatric, reproductive isolation), human evolution (brain size & lactose tolerance)

### Environmental management

*2nd year master students*

Projects conception, budgetization, presentation in front of territorial actors

### Agrégation preparatory classes

*2nd year master students*

Oral exam preparation: *Living organisms in the soil*

### Biodiversity monitoring

*Professional conservationists, 1st year master students*

-   Field methods & protocol to monitor mammals, small mammals, birds

-   Quantitative estimates

-   Data analysis (ANOSIM)


### Interventions in school & Tutoring

-   Preparation for high school national examination (Baccalauréat) in Physics and Mathematics

-   Presentation of research project, curses

-   Teaching the tidal ecosystem
